### PR TITLE
add cpm.py

### PR DESCRIPTION
**Pull request by dynaryu**
1. create BNS_JT folder for python module
2. create cpm.py 
3. create BNS_JT/tests/test_cpm.py

### CODE REVIEW

**Comment by dynaryu** [comment]
````
d <-1 
f <- 1
```

**Comment by jieunbyun** [comment]
Oh and for the current Matlab version, "isCompatible" function is somehow misplaced.. It'd be great if it could be placed correctly in the upcoming python version.

**Comment by jieunbyun** [comment]
As a test example, we can use this one:
image

**Comment by dynaryu** [comment]
- [x] add variable class
- [ ] need test for iscompatible; compatible takes C, variables, checkVars, checkStates, vInfo. Can you make some examples? 
- [ ] same kinds of tests are needed for the operations of sum, product 
- [ ] once I implement the basic operations, then I can add the simple bridge example.

**Comment by dynaryu** [comment]
> Oh and for the current Matlab version, "isCompatible" function is somehow misplaced.. It'd be great if it could be placed correctly in the upcoming python version.

I put it under cpm.py where Cpm class is defined.

**Comment by dynaryu** [comment]
> As a test example, we can use this one: image

Given the test example, can you provide input and output for testing? For instance, 

instance of Cpm class (variables, numChild, C, p)
instance of variable class (B, value)
isCompatible
product
sum
etc...

**Comment by jieunbyun** [comment]
Oh by the way, there is a typo in the example. P(X2|H) has p=[0.95 0.05 0.85 0.15]' -- The second element needs be changed from 0.15 to 0.05.

**Comment by dynaryu** [comment]
example for *condition* should be provided prior to *product*, as *condition* is utitlised in the *product*.

**Pull request merged**
